import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../globalStyles/normalise.css";
import "../globalStyles/globals.scss"

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "1Key",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
